### ISSUE TITLE
Investigate profiling performance in frontend

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1478]
As part of https://github.com/rilldata/rill-developer/issues/1316, we profiled the `spending.parquet` dataset (~170 MB), which requires ~1k HTTP queries. With a pool size of 10, that runs in about 2.5s in a direct benchmark (making 1k separate HTTP requests from a script), but takes ~12 seconds when running in the browser. [Here's](https://github.com/rilldata/rill-developer/tree/b91008ccd575968edba924f8688186f98ad38619/examples/spending) the example project.

- [x] Investigate if the overhead is due to the way the browser makes HTTP queries or whether it's due to other overhead (such as `svelte-query` maybe being slow at this scale). We can test this with a plain HTML file that uses `Promise.all` and `fetch` to run the benchmark.

 If it's the actual HTTP overhead, we could solve this by adding a batch query endpoint with streaming results (in fact, this solution might also make sense if svelte-query overhead is the problem)

**Comment by nishantmonu51** [comment]
Some observations while I was playing around with the dataset - 
1. Tried to compare with prev version of Rill and confirmed performance regression from ~2-3 sec to 14 sec on my local setup. 
2. Tried few small patches on frontend to experiment and removing the HTTPQueryQueue from the path helped. In order to make the queue not limit things, I increased the limit from 5 to 5K, and overall page load time reduced to 3-4 sec. 

The main reason for having a request queue was to enforce priority and ordering from the application side. 
With profile result caching improvements on runtime side and concurrency improving runtime perf even further, I wonder do we really need the queue on applications side to enforce a priority ordering ? 
- If not a must-have, I would vote for just getting rid of it for now and add it back when/if we need it, maybe schedule it along with virtualization work. 
- Alternatively, we can also rethink about a better implementation for it. 

@hamilton @begelundmuller @AdityaHegde : What are your thoughts on this?

**Comment by AdityaHegde** [comment]
There was a bug in the code with an unnecessary wait. After fixing it here are the results,
On main,
~14 sec on 1st run
<img width="1648" alt="Main - No Cache" src="https://user-images.githubusercontent.com/3214541/208881120-1f555a48-4961-4757-ad3c-d2f46b66bca4.png">
~11 sec on successive runs
<img width="1648" alt="Main - No Cache" src="https://user-images.githubusercontent.com/3214541/208881120-1f555a48-4961-4757-ad3c-d2f46b66bca4.png">

After the fix (#1501),
~9sec on 1st run
<img width="1648" alt="Branch - No Cache" src="https://user-images.githubusercontent.com/3214541/208881112-8518c914-d053-48b7-9971-436a8f370675.png">
~6sec on successive runs
<img width="1582" alt="Branch - Cache" src="https://user-images.githubusercontent.com/3214541/208881097-38aa7034-e19b-4aee-9fa5-ef6c5dc31828.png">
~4sec on successive runs with batch size = 20 (was ~9sec on 1st run)
<img width="1599" alt="Branch - Cache Size=20" src="https://user-images.githubusercontent.com/3214541/208881106-be2819df-e2bc-4f5a-a45f-5ce036f48124.png">

**Comment by begelundmuller** [comment]
I setup the benchmark as a `.html` file using `Promise.all` and `fetch`, and ran it from the browser. You can see the code [here](https://github.com/rilldata/rill-developer/blob/conn_pool/examples/spending/benchmark.html). Here are the results:

- When the cache is not hydrated, the Go benchmark takes 5.084938917s and the browser benchmark takes 6.01s
- When the cache is hydrated, the Go benchmark takes 0.718449625s and the browser benchmark takes 0.854s

<img width="1912" alt="Screenshot 2022-12-21 at 12 42 48" src="https://user-images.githubusercontent.com/791356/208898790-c08d35cf-79bf-4f60-9f47-40a1eb7df61e.png">
<img width="1912" alt="Screenshot 2022-12-21 at 12 43 17" src="https://user-images.githubusercontent.com/791356/208898800-917c3389-ad9d-4edf-8ff3-d0f02367348c.png">

**Comment by begelundmuller** [comment]
I tried @AdityaHegde's PR for comparison on my own machine. I'm getting similar results, 9.59s when cache is not hydrated and 4.51s when cache is hydrated.

Compared to the browser benchmark in my comment above, this indicates frontend overhead (svelte-query, frontend queue, animations, etc.) is currently about 3.5s. 

<img width="1912" alt="Screenshot 2022-12-21 at 12 59 39" src="https://user-images.githubusercontent.com/791356/208900531-25471450-fb16-405b-83f5-8a550658bb0f.png">

<img width="1912" alt="Screenshot 2022-12-21 at 12 59 04" src="https://user-images.githubusercontent.com/791356/208900544-b05d3ed3-0964-4032-8e0f-b25f1c82c9c9.png">

**Comment by begelundmuller** [comment]
I don't know if this is it, but I wouldn't be surprised if `svelte-query` isn't designed to perform at 1k separate concurrent queries. It probably updates the DOM for each result? 

If that's the case, I still think we should consider using a batch query endpoint with streaming results, where we run one query batch per model/dashboard. For state management, we could wrap it in a custom cache that a) triggers DOM updates on a fixed interval (e.g. 0.25s), b) can be invalidated using just the model/dashboard name. This would mean that instead of each component making its own HTTP request, a parent component would make one batched request, and then pass the results into children components. 

While HTTP is very performant, making one request with streaming results instead of 1k separate requests might still give us a few 100ms speedup on localhost. And for a future cloud offering, it would anyway be nicer from a routing, authentication and logging perspective.

**Comment by hamilton** [comment]
Thanks for looking into this everyone.

I would be in favor of making one request w/ streaming results as @begelundmuller suggests, and refactoring the column profile components to consume the stream rather than query these individually from the components themselves. This should be quite straightforward to d. The stream of updates could easily be put into a svelte store at the parent component level and then the data from that store directly passed into the child components.

I think this will also probably drastically reduce the queueing complexity & fix some of the jitteriness in `main` right now; the first thing I'd want to do is get the `ProfileColumn` results along with null %s and cardinalities, so I can establish the order ASAP, and then the numeric histograms + the timestamp area plot.

**Comment by hamilton** [comment]
We could also consider removing any / all animations as an exercise to see how much jank this adds. From experience, I know it _does_ add some, but typically not enough to be concerned about this latency ~ mostly, it just looks janky b/c there are too many histograms and bar charts to animate at once.

**Comment by begelundmuller** [comment]
I created an issue with an initial proposal for the query batch API here: https://github.com/rilldata/rill-developer/issues/1521. 

@hamilton, to quickly address your points:

- You still pass a priority for each query in the batch. The queries will be resolved and streamed back in priority order with the exception of queries with cached results, which will be streamed back immediately.
- Cancelling the HTTP request will cancel all queries in the batch. However, HTTP request cancellation on http1 is not well documented, so we'll do some testing first to make sure the signal propagates quickly.
