### ISSUE TITLE
Add default time selectors to metrics config

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill#1704]
- [x] Move `getSelectableTimeRanges` to server-side
- [x] Move (and unify) time control types `time-control-types.ts` to the backend.
- [x] Add support for `default_time_grain`, `default_time_range`, `time_grains` (list) key in YAML/Catalog
- [x] Add UI selector for default time range
- [x] Add UI selector for default time grain
- [x] Add UI selector for available time grains
- [x] Move away from native selectors and use custom menu and menu item component for Metric selectors
- [x] Create a responsive layout for displaying selectors, quick metrics button and error/warning callouts.

**Comment by pjain1** [comment]
@djbarnwal few questions -
1. I don't see any usage of `getSelectableTimeRanges` (present in `time-range-utils.ts`), am I missing something, Is it `getSelectableTimeRangeNames` ? Also trying to understand the motivation to move this method as I don't much logic or server dependency in the method.
2. `TimeGrain` and  `TimeSeriesTimeRange` types are present in `index.schema.ts` which is auto generated based on grpc spec. However `TimeRangeName` is not present because its not part of `TimeSeriesTimeRange` message in api.proto file but its present in `time-control-types.ts`. Did we miss it in api spec ?

**Comment by begelundmuller** [comment]
Just adding some thoughts:

1. If we don't allow customizing the selectable time ranges in the code file YAML, then I would vote for just hard-coding those options in the UI.
2. As I just wrote [in the other issue](https://github.com/rilldata/rill-developer/issues/1680), instead of hard-coding these as an enum in the API, I would vote for using something something more genereic, like ISO 8601 as @pjain1 proposed, in the artifacts (which the UI could then format nicely).

**Comment by pjain1** [comment]
@djbarnwal can you confirm the method to move, is it `getSelectableTimeRangeNames` ? For the 2nd point I will just add `TimeRangeName` to `TimeSeriesTimeRange` message in api.proto file.

**Comment by djbarnwal** [comment]
The method to move is `getSelectableTimeRanges`. It's present in `TimeRangeNameSelector.svelte` file. The motivation was to move this logic to server-side and fetch the results from the `/meta` endpoint directly

**Comment by pjain1** [comment]
so it seems like selectable time ranges should be part of `V1MetricsView` response returned from getting metrics view catalog entry from the runtime ?

**Comment by begelundmuller** [comment]
Hey, this is my current proposal:

1. In UI, the list of available time *grains* (e.g. "day", "month", etc.) should be all or a subset of the values in `V1TimeGrain`
2. In UI, the list of available time range options (e.g. "last 30 days", etc.) should be hard-coded as a list/enum in the frontend. It will not be provided by the backend or be customizable in the YAML.
3. In YAML, the `default_time_range` will accept an [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) value (e.g. "P30D", "P1W"). The frontend should map the human friendly names (like "last 30 days") to the ISO representation before writing out to the YAML.
4. In `V1MetricsView`, there will be a `defaultTimeRange` string field containing the ISO8601 value. (It will have been validated, so you know this can't contain random strings).
5. In YAML, if the user manually changes `default_time_range` to an ISO 8601 duration not supported by the UI (i.e. not available in the hard-coded list, e.g. "P20D"), Applications should decide how to handle it. I would propose just showing the ISO8601 value directly (but then you would need to support it when computing the time range to request data for). Another alternative is to just print "unsupported time range".

@pjain1 can you confirm this looks right from the backend perspective? @djbarnwal and @hamilton does this sound good to you?

**Comment by pjain1** [comment]
This looks fine to me.

**Comment by hamilton** [comment]
This sounds goo to me @begelundmuller ~ thanks for thinking this through.

**Comment by ajbouh** [comment]
I've gone through the above comments and the comments in related issues and am having trouble understanding whether or not it will be possible to see data for business-relevant time periods. For example specific months/quarters/years or month/quarter/year to date.

Apologies if I'm missing something obvious!
