### ISSUE TITLE
"Quick Metrics" button should generate SUM measures for each numeric column 

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#1712]
Request from Scott.

**Is your feature request related to a problem? Please describe.**
It's laborious for him to create a bunch of measures when he creates a new dashboard. He would prefer to edit existing measures rather than create new ones from scratch.

**Describe the solution you'd like**
He would like the "Quick Metrics" button to generate basic "sum of" measures for all numeric columns.

**Additional context**
This functionality exists in legacy Rill Dash.

**Comment by magorlick** [comment]
I appreciate the input! I am not sure if this is the right experience leveraging "Quick Start" because it is making too many assumptions about what the contents of numeric values mean, but in the fullness of time we should make a better metrics editing experience to quickly define more expressions over many columns than count(*).
