### ISSUE TITLE
[Navigation] Load the artifact for the page after we start rendering it

### ISSUE THREAD

**Issue by AdityaHegde** [rilldata/rill#1724]
Currently we make a call to fetch the catalog and artifact of the item in the page along with a config object. All these happen before we even start rendering. If there is profiling running this could get blocked.

If we have cached data then we should start rendering the page and asynchronously refetch the data. This would feel like the page has loaded quickly to the user.

**Comment by hamilton** [comment]
@AdityaHegde a question: I think we load the code file in `+page.ts` because we need to check it for errors. If the code file exists but it’s not in the catalog, then we’re assuming it has an error of some kind in it. In some cases, that error requires us to surface a 400 or 500 error in some way. Is the approach you have in mind going to cover the case where we may need to actually return an error page to the user?

**Comment by AdityaHegde** [comment]
This is no longer an issue with async reconciling.
