### ISSUE TITLE
Runtime: Support profiling columns nested in `STRUCT` types

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill#1735]
`STRUCT` columns usually represent a nested column of some kind. The values have the same schema. Therefore, we can in theory profile each field of a `STRUCT` and generate a profile.

Unfortunately in our case, I get a `binder error` if I attempt this: 

```
"Binder Error: Referenced column \"raw_log.id\" not found in FROM clause!
Candidate bindings: \"transactions.raw_log\"\nLINE 1: ...nt(*) AS count FROM \"transactions\" GROUP BY \"raw_log.id\" ORDER BY count DESC, value...\n                                                  ^"
```

Not 100% sure how this should work, but I'm seeing now that we're so close to being able to support a better story with `STRUCT` columns.

**Comment by begelundmuller** [comment]
We probably don't want to remove the escaping of input columns as that creates other problems. Some other ideas:

- Check if column name exists in table. If not, parse dots (or square brackets) and treat as struct access.
- Instead of a single column name, the API should accept an array of names designating a struct access "path". (One array entry would be a regular column profiling.)
- Add a separate struct profiling analytical API, that recursively profiles the struct and returns the full result. (This would probably have better performance as well.)

Added this issue to platform backlog.

**Comment by hamilton** [comment]
Moving this out of any specific version until the backend work gets scoped by platform
