### ISSUE TITLE
Runtime: BigQuery connector

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#2343]

**Comment by k-anshul** [comment]
@begelundmuller This is what I am thinking as a high level approach for a MVP connector that would fit with our existing connector design. 
1. The user will be expected to provide a SQL query. The results of this query will be used for creating a table. 
2. Run the query using google cloud go sdk.
3. Use the results of query to create local file(s) in `parquet`/`json` format. `CSV` files have limitations that nested fields can't be easily dumped. Even big query file dump to gcs also does not support `CSV` for nested fields.
4. Unfortunately this step is non-trivial since the SDK has no support to do so natively. We can only dump query results to files to gcs.
5. The challenge in writing `parquet` files will be to convert query schema to parquet file schema. We will have to write this conversion ourself. 
6. `JSON` format saves this schema conversion step. However we need to ingest data from `json` files which may not be 100% reliable. `JSON` files may be inefficient as well. 

I am in favour of using parquet format. I looked at the schema conversion and it should be doable.

Please let me know if there is any other approach that can be taken here.

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill/pull/2790
