### ISSUE TITLE
Incorrect "Percent of Total" calculation when applying filters to leaderboards

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3162]
To reproduce:
1. Enable the "Percent of Total" column on a leaderboard and apply a filter to it.
2. Check a different leaderboard's "Percent of Total" column.

Expected Behavior: The denominator in the "Percent of Total" calculation should adjust to reflect the filtered dataset.

Actual Behavior: The "Percent of Total" column remains unchanged, failing to account for the applied filter.

**Comment by bcolloran** [comment]
I had originally implemented the percent of total as you describe it, but it was specifically requested that we change the behavior to use the unfiltered total for calculating percentages. That update was made here and approved by Nishant who was involved in those conversations. https://github.com/rilldata/rill/pull/2799. 

 I'm not sure the current behavior is the best possible approach, but it's what was requested and approved, so I think we need a proposal/PRD before making change. Closing this issue as the calculation is actually correct according to the most recent spec.

**Comment by bcolloran** [comment]
@begelundmuller, do we have an API that would support use case of getting per-leaderboard totals that would sum to 100% including the case of leaderboards with some rows that are shown but filtered out? Would calculating these extra totals run into any of the same [perf issues described in the discussion of the "others" line](https://www.notion.so/rilldata/Incorporate-Others-line-in-Leaderboards-168cce476c06402a8b6e89346978ba61)? (IIRC there was some concern about summing per leaderboard in that context, don't know if this would be similar)

(see also https://rilldata.slack.com/team/U03BKKKLV6F)

**Comment by avaitla** [comment]
I think the spec is wrong, the percent should be the percent in the remaining filtered set from all our use cases that is what is useful (just like how measures only include the filtered set).

**Comment by bcolloran** [comment]
@avaitla Hey just wanted to let you know that we have discussed this and agree with you, and we're looking into a solution

**Comment by begelundmuller** [comment]
@bcolloran The toplist API does not return per-leaderboard totals. Previously, I believe the dashboard separately called the totals API for each toplist.

We can look into adding it to the toplist API if needed – but under the hood, it's two different queries, so whether one API runs the two queries or it's two different APIs running one query is not a big difference from a performance perspective.

IIRC, there was previously a desire to use two APIs instead of one for this (for more incremental rendering, I would guess). 

To unblock this work, I would probably recommend going with the two calls approach, and then we can separately investigate baking it into the toplist API if needed.

**Comment by bcolloran** [comment]
fixed in https://github.com/rilldata/rill/pull/3331
