### ISSUE TITLE
Commented code at end of model causes error

### ISSUE THREAD

**Issue by cohenscottr** [rilldata/rill#3464]
**Describe the bug**
Adding comment to a sql model at end of model causes issue. At beginning or middle of model does not seem to cause the same.

**To Reproduce**
1. Comment a line at end of sql model
2. Produces build error below

<img width="299" alt="image" src="https://github.com/rilldata/rill/assets/82397988/0c0a4e6d-34b9-4635-9b34-5784be93a890">

Additional reference:
https://discord.com/channels/959796421832343562/959801632151969792/1173429640866562099

**Expected behavior**
No error

**Screenshots**
See above

**Comment by k-anshul** [comment]
We run following query while creating a model :
```
create or replace view test_view as (__sql__);
```

The problem is that if there is some commented code at the end, this gets converted to :
```
create or replace view test_view as (select * from test--wello horld\n);
```
Anything after the `--` in the same line is identified as comment making the sql statement incomplete. I can see two ways to solve this :
1. Add an additional `\n` to make the query as 
```
create or replace view test_view as (select * from test--wello horld\n
\n);
```
Need to see if it can solve for all cases.

2. Remove the commented out code at the end using the parser. This is slightly more involved solution but seems better.
