### ISSUE TITLE
add images with new default colors to the "Welcome to Rill" first run page

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#3899]
Part of #3863, but a discrete and separate task.

Images can be generated using the branch in PR #3863, even before that branch merges.

Going from [this mock](https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=1987%3A35610&mode=design&t=Ga9Rh4pu4tJANRIc-1), we'll need the following images:
- [ ] line charts for "cost monitoring" card
- [ ] dimension table for "OpenRTB" card
- [ ] profiler for "Github Analytics" card
- [ ] background swoopies

@jkhwu can you provide links to the final assets you want used in those location when they are ready? Thanks!

(note that current background image is quite grainy -- looks like compression artifacts, we should watch out for that)

**Comment by mindspank** [comment]
If we are running low on time before release let's just update the main logo and background art for 0.40. We can swap out the tiles in 0.41

**Comment by jkhwu** [comment]
Updated thumbnail screenshots for the first two example project cards. The third is unchanged because we haven't determined if/how the new colors should affect the column profiles in the right panel yet.
    
https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=1631-35455&mode=design&t=BkgjZVfS7TyqoZIL-11

**Comment by bcolloran** [comment]
closed by https://github.com/rilldata/rill/pull/3927
