### ISSUE TITLE
Fix alignment of data and column headers in dimension detail view

### ISSUE THREAD

**Issue by AndrewRTsao** [rilldata/rill#3904]
When drilling down into the dimension detail view, the data is not always properly aligned with the column headings, which can lead to confusion / reduced readability for the end user. Notably, numeric values should be right-aligned. 

Additional context: https://discord.com/channels/959796421832343562/959801632151969792/1199824015536160829

**Comment by AndrewRTsao** [comment]
FYI @jkhwu @djbarnwal

**Comment by mindspank** [comment]
Generally the 3.5 rule is good to follow here:

1. Numbers are right aligned
2. Text are left aligned
3. Headers should align with their data
3.5. Never center align

In our case the spans containing the data is actually declaring `text-align: right` however since they don't fill the entire cell and cells have right sided padding we would need some refactoring here

**Comment by jkhwu** [comment]
Alex's guidelines sound good to me.

**Comment by djbarnwal** [comment]
Fixed here #4278
