### ISSUE TITLE
Bug: Folders with whitespace breaks filelisting

### ISSUE THREAD

**Issue by mindspank** [rilldata/rill#4786]
Create a folder called "Finance Dept". 
Observe that no files within the folder can be listed

![image](https://github.com/rilldata/rill/assets/1181922/1b6a3368-b0de-425d-b2a2-834a5c6de06e)
![image](https://github.com/rilldata/rill/assets/1181922/a8f93810-130f-4a3f-bd42-c1882a412090)

**Comment by begelundmuller** [comment]
I think this might be the frontend encoding the file name twice – because it looks like the backend handles it correctly:

<img width="216" alt="Screenshot 2024-05-01 at 10 22 47" src="https://github.com/rilldata/rill/assets/791356/4c86d43c-e91f-4130-a673-c846207274d4">
<img width="692" alt="Screenshot 2024-05-01 at 10 22 41" src="https://github.com/rilldata/rill/assets/791356/9e8a14ad-8073-41ed-a752-2fb706019e7c">
