### ISSUE TITLE
Dashboard: apply time zone to Leaderboard query

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4957]
The requests to `compare-toplist` do not currently include the selected time zone.

[More context in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1716508002693279)

**Comment by djbarnwal** [comment]
The `compare-toplist` does not time a timezone as the dates are already provided in UTC.

For the timeseries query,  we have to aggregate into periodic buckets for displaying the chart. This is not the case for leaderboard as no bucketing is required between start and end time.

The dates change because of the time preset selected. For ex-  Last 24 hours for PST might be different than Last 24 hours IST because of a shift of 30 mins for getting a full hour. But in general the time string passed is in UTC.
