### ISSUE TITLE
readonly mode should not allow arbitrary file listing or listing sensitive project variables/env values

### ISSUE THREAD

**Issue by dweinstein** [rilldata/rill#5039]
**Is your feature request related to a problem? Please describe.**
rill CLI currently starts a server that allows listing files (e.g., `.env` and allows retrieval of (potentially) sensitive project variables, like postgresql URL with username/passwords)

**Describe the solution you'd like**
Readonly mode should only display dashboards and allow basic export data.

**Describe alternatives you've considered**

**Additional context**
A developer could browser to a website, while using rill developer CLI, (`rill start`) that makes an XHR to the developer's machine via `fetch('http://localhost:9009/v1/instances/default?sensitive=true')` to grab the values and possibly gain access to sensitive information. This could leak sensitive information

**Comment by mindspank** [comment]
@begelundmuller related to what we discussed previously.

**Comment by begelundmuller** [comment]
So there are two problems here:
1. The regular experience does not apply CORS and CSP policies that guard against XHR to localhost from other websites. Changing it to only allow requests from `localhost` may break the experience for people who self-host local Rill today.
2. The `--readonly` flag does not block access to endpoints that expose access to variables or the local file system.

**Comment by begelundmuller** [comment]
Since the local Rill experience is not really designed for self-hosting (even thought it's possible), we will prioritize problem 2 separately. However, we should fix the CORS and CSP issue immediately.

@Kavinjsir The problem here is basically that the current CORS policy allows calls from all origins. The changes needed are:
- Only allow calls from the HTTP host, which is `localhost:9009` by default (replacing port 9009 with the port passed to `--port`).
- Support additional CORS origins with a `rill start --allowed-origins host1,host2,...` flag to not break self-hosted instances of Rill.
- Investigate and maybe add a CSP policy for the local UI. We have one for the cloud UI, but not the local one. I'm not entirely sure what if anything it should contain – maybe browser defaults are sufficient.

Here are some pointers for code to edit:

- The entrypoint for the `rill start` command is here: https://github.com/rilldata/rill/blob/b67474d7b4fd3770f21999f0c3e96a3e86c216b7/cli/cmd/start/start.go#L25
- When running `rill start`, it initializes and starts the runtime's HTTP server with a few additional local endpoints mounted. It currently configures the allowed origins to `*` here: https://github.com/rilldata/rill/blob/b67474d7b4fd3770f21999f0c3e96a3e86c216b7/cli/pkg/local/app.go#L380
- The actual code that implements CORS is defined in the runtime's HTTP server here: https://github.com/rilldata/rill/blob/b67474d7b4fd3770f21999f0c3e96a3e86c216b7/runtime/server/server.go#L228

After making the changes, you should test that the app still works on localhost, and that XHR requests from other domains to localhost fail with CORS errors.
