### ISSUE TITLE
Unable to execute SQL other than SELECT with DuckDB Connector 

### ISSUE THREAD

**Issue by kenchan0130** [rilldata/rill#6261]
**Describe the bug**

When using the DuckDB connector, the source SQL statement will not accept anything but select.

**To Reproduce**

1. Go to 'Source'
2. Edit sql

```
failed to ingest source: failed to parse sql: Only SELECT statements can be serialized to json!
```

**Expected behavior**

Like the DuckDB CLI, I would expect it to be able to execute more than just select statements.

**Screenshots**

![](https://github.com/user-attachments/assets/079d4c01-50c1-4ad9-a804-921f2b937373)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Google Chrome
 - Rill Version: 0.51.3

**Additional context**

I have confirmed that it is working as expected in the DuckDB CLI.

**Comment by begelundmuller** [comment]
Can you try changing your `sample.yaml` file to:
```yaml
type: model
materialize: true
sql: select * from read_json('s3://xxxxx/*.jsonl', auto_detect=true, format='auto')
```

By using `type: model` instead of `type: source`, it circumvents some code that intercepts `s3://` strings in DuckDB sources dating back to before DuckDB supported S3 credential chains (we will soon remove it since DuckDB has gotten very good at handling AWS credentials now). I can't quite explain why the legacy logic doesn't work for you here, but before triaging deeper I'm curious if this change fixes it for you.

Also note that if you updated your AWS config after starting Rill, you may need to restart Rill for it to take effect.

**Comment by kenchan0130** [comment]
@begelundmuller 

I have changed the configuration to the one you provided and it worked as expected.
It is very helpful for me to know those specifications.

**Comment by begelundmuller** [comment]
Happy to hear that it worked!

**Comment by kenchan0130** [comment]
Thank you for your support.
